# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u5206\u7c7b\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u5173\u952e\u8bcd')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u4ea7\u54c1\u540d\u79f0')),
                ('spec', models.CharField(choices=[('1', '\u5927\u53f7'), ('2', '\u4e2d\u53f7'), ('3', '\u5c0f\u53f7')], max_length=1, verbose_name='\u4ea7\u54c1\u578b\u53f7')),
                ('stock', models.IntegerField(default=100, verbose_name='\u5e93\u5b58\u6570\u91cf')),
                ('price', models.DecimalField(decimal_places=2, default=10.0, max_digits=8, verbose_name='\u4ea7\u54c1\u4ef7\u683c')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='\u4ea7\u54c1\u63cf\u8ff0')),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='\u4ea7\u54c1\u7c7b\u522b')),
                ('key', models.ManyToManyField(to='product.Keyword', verbose_name='\u5173\u952e\u8bcd')),
            ],
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
